name: Lint and PSR Check

on:
  pull_request:
    branches:
      - development

jobs:
  lint-and-psr-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install

      - name: Run linter
        run: php -l .

      - name: Run PSR check
        run: php vendor/bin/phpcs --standard=PSR12 .
