name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PROD_DEPLOYER_PRIVATE_KEY }}

      - name: Deploy to Production Server 1
        env:
          SSH_USER: ${{ secrets.SSH_PROD_DEPLOYER_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PROD_DEPLOYER_PASSWORD }}
          SERVER_IP_1: ${{ secrets.PROD_SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP_1 << 'EOF'
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            RELEASE_DIR="/var/www/apply.shoprite.jobs/releases/$TIMESTAMP"
            CURRENT_DIR="/var/www/apply.shoprite.jobs/current"
            SHARED_DIR="/var/www/apply.shoprite.jobs/shared"
            sudo -u www-data mkdir -p $RELEASE_DIR
            sudo -u www-data git clone -b main git@github.com:Tenutech/Shoprite.git $RELEASE_DIR
            cd $RELEASE_DIR
            sudo -u www-data ln -nfs $SHARED_DIR/.env
            sudo -u www-data ln -nfs $SHARED_DIR/storage
            sudo -u www-data composer install --no-dev --optimize-autoloader
            sudo chown www-data:www-data -R /var/www/apply.shoprite.jobs
            sudo -u www-data npm i
            sudo -u www-data npm run build
            # php artisan migrate --force
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            sudo -u www-data ln -sfn $RELEASE_DIR $CURRENT_DIR
            ls -dt /var/www/apply.shoprite.jobs/releases/* | tail -n +3 | xargs sudo rm -rf
          EOF

      # - name: Rsync to Production Server 2
      #   env:
      #     SSH_USER: ${{ secrets.SSH_PROD_DEPLOYER_USERNAME }}
      #     SSH_PASSWORD: ${{ secrets.SSH_PROD_DEPLOYER_PASSWORD }}
      #     SERVER_IP_1: ${{ secrets.PROD_SERVER_IP }}
      #   run: |
      #     sudo apt-get install -y sshpass
      #     sshpass -p $SSH_PASSWORD rsync -avz --delete -e 'ssh -p 50001' $SSH_USER@$SERVER_IP_1:/var/www/apply.shoprite.jobs/releases/ $SSH_USER@$SERVER_IP:/var/www/apply.shoprite.jobs/releases/