name: Deploy to Prod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H tenutech@tenutech.asuscomm.com >> ~/.ssh/known_hosts
      
      # Add steps to deploy to the production environment
      - name: Deploy to Production Server
        run: |
          ssh tenutech@tenutech.asuscomm.com -p 2222 'echo "Deploying to Dev!"'
