name: Deploy to Dev

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.4'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.4'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run production

      - name: Execute tests
        run: vendor/bin/phpunit --verbose

      - name: Generate optimized autoload files and clear cache
        run: composer dump-autoload --optimize && php artisan optimize:clear

  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: tenutech.asuscomm.com
          username: tenutech
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            cd /var/www/orient
            git pull origin master
            composer install --no-dev --optimize-autoloader
          # php artisan migrate --force
            php artisan optimize
          # php artisan up
