name: Deploy to Development

on:
  push:
    branches:
      - development

jobs:
  Checkout:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set_timestamp.outputs.timestamp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Timestamp
        id: set_timestamp
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "timestamp=$TIMESTAMP" >> $GITHUB_ENV
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

  SetupSSH:
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DEV_DEPLOYER_PRIVATE_KEY }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [Checkout, SetupSSH]
    outputs:
      release_dir: ${{ steps.deploy.outputs.release_dir }}
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DEV_DEPLOYER_PRIVATE_KEY }}
          
      - name: Deploy to Development Server
        id: deploy
        env:
          SSH_USER: ${{ secrets.SSH_DEV_DEPLOYER_USERNAME }}
          SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
          TIMESTAMP: ${{ needs.Checkout.outputs.timestamp }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << 'EOF'
            export TZ="Africa/Johannesburg"
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            RELEASE_DIR="/var/www/dev.apply.shoprite.jobs/releases/$TIMESTAMP"
            CURRENT_DIR="/var/www/dev.apply.shoprite.jobs/current"
            SHARED_DIR="/var/www/dev.apply.shoprite.jobs/shared"

            sudo -u www-data mkdir -p $RELEASE_DIR

            sudo -u www-data git clone -b development git@github.com:Tenutech/Shoprite.git $RELEASE_DIR

            cd $RELEASE_DIR

            sudo -u www-data ln -nfs $SHARED_DIR/.env $RELEASE_DIR/.env
            sudo -u www-data ln -nfs $SHARED_DIR/storage $RELEASE_DIR/storage

            sudo -u www-data composer install --no-dev --optimize-autoloader

            sudo chown www-data:www-data -R /var/www/dev.apply.shoprite.jobs/

            sudo -u www-data npm i

            sudo -u www-data npm run build
          EOF

  FinalizeDeployment:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DEV_DEPLOYER_PRIVATE_KEY }}

      - name: Finalize Deployment
        env:
          SSH_USER: ${{ secrets.SSH_DEV_DEPLOYER_USERNAME }}
          SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << 'EOF'
            RELEASE_DIR=$(ls -dt /var/www/dev.apply.shoprite.jobs/releases/* | head -n 1)
            cd $RELEASE_DIR

            php artisan migrate --force

            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache

            sudo -u www-data ln -sfn $RELEASE_DIR /var/www/dev.apply.shoprite.jobs/current

            ls -dt /var/www/dev.apply.shoprite.jobs/releases/* | tail -n +4 | xargs sudo rm -rf
          EOF