name: Deploy to Development

on:
  push:
    branches:
      - development
  workflow_dispatch:


jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
<<<<<<< HEAD
          ssh-private-key: ${{ secrets.SSH_DEPLOYER_PRIVATE_KEY }}

      - name: Deploy to Development Server
        env:
          SSH_USER: ${{ secrets.SSH_DEPLOYER_USERNAME }}
          SERVER_IP: 41.76.109.198
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << ‘EOF’
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            RELEASE_DIR=“/var/www/dev-shoprite.tenutech.com/releases/$TIMESTAMP”
            CURRENT_DIR=“/var/www/dev-shoprite.tenutech.com/current”
            SHARED_DIR=“/var/www/dev-shoprite.tenutech.com/shared”
            sudo -u www-data mkdir -p $RELEASE_DIR
            sudo -u www-data git clone -b development git@github.com:Tenutech/Shoprite.git $RELEASE_DIR
            cd $RELEASE_DIR
            sudo -u www-data ln -nfs $SHARED_DIR/.env
            sudo -u www-data ln -nfs $SHARED_DIR/storage
            sudo -u www-data ln -nfs $SHARED_DIR/auth.json
            sudo -u www-data composer install --no-dev --optimize-autoloader
            sudo chown www-data:www-data -R /var/www/dev-shoprite.tenutech.com/
=======
          ssh-private-key: ${{ secrets.SSH_DEV_DEPLOYER_PRIVATE_KEY }}

      - name: Deploy to Development Server
        env:
          SSH_USER: ${{ secrets.SSH_DEV_DEPLOYER_USERNAME }}
          SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << 'EOF'
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            RELEASE_DIR="/var/www/dev.apply.shoprite.jobs/releases/$TIMESTAMP"
            CURRENT_DIR="/var/www/dev.apply.shoprite.jobs/current"
            SHARED_DIR="/var/www/dev.apply.shoprite.jobs/shared"
            sudo mkdir -p $RELEASE_DIR
            sudo chown www-data:www-data -R /var/www/dev.apply.shoprite.jobs/
            sudo -u www-data git clone -b development git@github.com:Tenutech/Shoprite.git $RELEASE_DIR
            cd $RELEASE_DIR
            sudo rm -R $RELEASE_DIR/storage
            sudo ln -nfs $SHARED_DIR/.env .env
            sudo ln -nfs $SHARED_DIR/storage storage
            sudo -u www-data composer install --no-dev --optimize-autoloader
            sudo chown www-data:www-data -R /var/www/dev.apply.shoprite.jobs/
>>>>>>> fb04c61281448542a60c90aaba9deb7be7bee475
            sudo -u www-data npm i
            sudo -u www-data npm run build
            # php artisan migrate --force
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            sudo -u www-data ln -sfn $RELEASE_DIR $CURRENT_DIR
<<<<<<< HEAD
            ls -dt /var/www/dev-shoprite.tenutech.com/releases/* | tail -n +3 | xargs sudo rm -rf
=======
            ls -dt /var/www/dev.apply.shoprite.jobs/releases/* | tail -n +3 | xargs sudo rm -rf
>>>>>>> fb04c61281448542a60c90aaba9deb7be7bee475
          EOF
