name: Deploy to Development

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shoprite_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.12.0
        with:
          php-version: 8.2.4
          extensions: pdo_sqlite, sqlite3, xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
            
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Set Up Environment
        run: |
          mkdir -p storage/framework/views storage/framework/cache
          mkdir -p database
          touch database/database.sqlite
          cp .env.testing .env
          chmod -R 775 storage
          php artisan config:cache
          php artisan cache:clear

      - name: Configure MySQL in .env
        run: |
          sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env.testing
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=shoprite_test/' .env.testing
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=user/' .env.testing
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' .env.testing
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env.testing

      - name: Wait for MySQL
        run: |
          sudo apt-get install -y mysql-client
          until mysql -h 127.0.0.1 -u user -ppassword -e "SHOW DATABASES;" > /dev/null 2>&1; do
            echo "Waiting for MySQL to be ready..."
            sleep 10
          done

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests with Coverage
        run: ./vendor/bin/pest --coverage-html build/coverage

      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/coverage

      - name: Create Coverage Report Link
        run: |
          echo "Coverage report available at: [Coverage Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)" >> $GITHUB_STEP_SUMMARY

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DEV_DEPLOYER_PRIVATE_KEY }}

      - name: Deploy to Development Server
        env:
          SSH_USER: ${{ secrets.SSH_DEV_DEPLOYER_USERNAME }}
          SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -p 50000 $SSH_USER@$SERVER_IP << 'EOF'
            export TZ="Africa/Johannesburg"
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            RELEASE_DIR="/var/www/dev.apply.shoprite.jobs/releases/$TIMESTAMP"
            CURRENT_DIR="/var/www/dev.apply.shoprite.jobs/current"
            SHARED_DIR="/var/www/dev.apply.shoprite.jobs/shared"

            # Create the release directory
            sudo -u www-data mkdir -p $RELEASE_DIR

            sudo chown www-data:www-data -R /var/www/dev.apply.shoprite.jobs/

            # Clone the repository
            sudo -u www-data git clone -b development git@github.com:Tenutech/Shoprite.git $RELEASE_DIR

            # Change to the release directory
            cd $RELEASE_DIR

            # Link the .env file and storage directory
            sudo rm -R $RELEASE_DIR/storage
            sudo ln -nfs $SHARED_DIR/.env .env
            sudo ln -nfs $SHARED_DIR/storage storage

            # Install dependencies
            sudo -u www-data composer install --no-dev --optimize-autoloader

            # Change ownership to www-data
            sudo chown www-data:www-data -R /var/www/dev.apply.shoprite.jobs/

            # Cache Laravel configurations and run optimizations
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            sudo -u www-data php artisan optimize

            # Run migrations
            sudo -u www-data php artisan migrate --force

            # Install npm dependencies and build assets
            # sudo -u www-data npm install
            # sudo -u www-data npm run build

            # Update the current symlink to the new release
            sudo -u www-data ln -sfn $RELEASE_DIR $CURRENT_DIR

            # Restart Supervisor to apply changes
            sudo supervisorctl reread
            sudo supervisorctl update
            sudo supervisorctl restart laravel-queue-worker:*

            # Remove old releases, keeping only the last two
            ls -dt /var/www/dev.apply.shoprite.jobs/releases/* | tail -n +3 | xargs sudo rm -rf
          EOF

          