name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PROD_DEPLOYER_PRIVATE_KEY }}

      - name: Deploy to Produciton Server
        env:
          SSH_USER: ${{ secrets.SSH_DEV_DEPLOYER_USERNAME }}
          SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -p 50000 $SSH_USER@$SERVER_IP << 'EOF'
            cd /home/support/shoprite_deployment && ansible-playbook -i inventories/production/hosts --extra-vars "branch=main env=prod" playbook-code-deploy.yml
          EOF